name: deploy on AWS
'on' :
  push:
    branches:
      - production

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkoutout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: oat431
          password: a7dfba31-e2ca-49b2-96a8-b701bce97ad4
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: oat431/se331-greenlake-frontend:latest
      -
        name: prepare the docker-compose run
        run: |
          mkdir vue-project-331
          cp docker-compose.yml vue-project-331/docker-compose.yml
          cd vue-project-331
          docker-compose -H tcp://54.146.210.137:5039 pull
          docker-compose -H tcp://54.146.210.137:5039 up -d 